trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: UseNode@1
  inputs:
    version: '18.x'

- script: |
    echo "Installing dependencies"
    npm install
    echo "Running tests"
    npm test
  displayName: 'Install and Test'
